image: node:latest

stages:
  - install
  - test
  - build

install:
  stage: install
  script:
    - npm install --verbose -f
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq rsync
  script:
    - npm run build

